// packages/ui/src/components/download-monitor.tsx
import { Download, FileDown } from "lucide-react";
import { useTranslation } from "react-i18next";
import { cn } from "@/lib/utils";
import { useDownloadStore } from "@/models/downloads";

function formatBytes(value: number) {
  if (!Number.isFinite(value) || value <= 0) return "—";
  const units = ["B", "KB", "MB", "GB"];
  const unit = Math.min(
    Math.floor(Math.log(value) / Math.log(1024)),
    units.length - 1,
  );
  return `${(value / 1024 ** unit).toFixed(unit > 1 ? 1 : 0)} ${units[unit]}`;
}

export function DownloadMonitor({ className }: { className?: string }) {
  const { t } = useTranslation();
  const download = useDownloadStore();

  if (!download.active && download.totalFiles === 0) return null;

  const percentage = Math.round(download.percentage);

  return (
    <section
      id="download-monitor"
      tabIndex={-1}
      aria-labelledby="download-monitor-title"
      aria-live="polite"
      className={cn(
        "border-border/80 bg-card/90 focus-visible:ring-ring overflow-hidden border shadow-sm backdrop-blur-xl focus-visible:ring-2 focus-visible:outline-none",
        className,
      )}
      data-testid="download-monitor"
    >
      <div className="border-border/70 flex items-center justify-between border-b px-3 py-2.5">
        <div className="flex min-w-0 items-center gap-2">
          <span className="bg-primary/10 text-primary flex size-7 shrink-0 items-center justify-center rounded-md">
            <Download className="size-3.5" aria-hidden="true" />
          </span>
          <div className="min-w-0">
            <h2 id="download-monitor-title" className="text-xs font-semibold">
              {t("downloadMonitor.title")}
            </h2>
            <p className="text-muted-foreground truncate text-[10px]">
              {download.kind === "java"
                ? t("downloadMonitor.javaRuntime")
                : t("downloadMonitor.gameFiles")}
            </p>
          </div>
        </div>
        <span className="text-primary font-mono text-xs font-bold">
          {percentage}%
        </span>
      </div>

      <div className="space-y-3 p-3">
        <div
          className="bg-muted h-1.5 overflow-hidden rounded-full"
          role="progressbar"
          aria-label={t("downloadMonitor.progress")}
          aria-valuemin={0}
          aria-valuemax={100}
          aria-valuenow={percentage}
        >
          <div
            className="bg-primary h-full rounded-full transition-[width] duration-300 motion-reduce:transition-none"
            style={{ width: `${percentage}%` }}
          />
        </div>

        <div className="flex items-start gap-2">
          <FileDown
            className="text-muted-foreground mt-0.5 size-3.5 shrink-0"
            aria-hidden="true"
          />
          <div className="min-w-0 flex-1">
            <p className="truncate font-mono text-[11px]">
              {download.currentFile ?? t("downloadMonitor.preparing")}
            </p>
            <div className="text-muted-foreground mt-1 flex justify-between gap-2 text-[10px]">
              <span>
                {download.totalFiles > 0
                  ? t("downloadMonitor.files", {
                      completed: download.completedFiles,
                      total: download.totalFiles,
                    })
                  : download.status}
              </span>
              <span>
                {download.totalBytes > 0
                  ? `${formatBytes(download.downloadedBytes)} / ${formatBytes(download.totalBytes)}`
                  : download.status}
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ui/src/lib/DownloadMonitor.svelte
<script lang="ts">
  import { listen } from "@tauri-apps/api/event";
  import { onMount, onDestroy } from "svelte";

  export let visible = false;

  interface DownloadEvent {
    file: string;
    downloaded: number; // in bytes
    total: number; // in bytes
    status: string;
    completed_files: number;
    total_files: number;
    total_downloaded_bytes: number;
  }

  let currentFile = "";
  let progress = 0; // percentage 0-100 (current file)
  let totalProgress = 0; // percentage 0-100 (all files)
  let totalFiles = 0;
  let completedFiles = 0;
  let statusText = "Preparing...";
  let unlistenProgress: () => void;
  let unlistenStart: () => void;
  let unlistenComplete: () => void;
  let downloadedBytes = 0;
  let totalBytes = 0;

  // Speed and ETA tracking
  let downloadSpeed = 0; // bytes per second
  let etaSeconds = 0;
  let startTime = 0;
  let totalDownloadedBytes = 0;
  let lastUpdateTime = 0;
  let lastTotalBytes = 0;

  onMount(async () => {
    unlistenStart = await listen<number>("download-start", (event) => {
      visible = true;
      totalFiles = event.payload;
      completedFiles = 0;
      progress = 0;
      totalProgress = 0;
      statusText = "Starting download...";
      currentFile = "";
      // Reset speed tracking
      startTime = Date.now();
      totalDownloadedBytes = 0;
      downloadSpeed = 0;
      etaSeconds = 0;
      lastUpdateTime = Date.now();
      lastTotalBytes = 0;
    });

    unlistenProgress = await listen<DownloadEvent>(
      "download-progress",
      (event) => {
        const payload = event.payload;
        currentFile = payload.file;

        // Current file progress
        downloadedBytes = payload.downloaded;
        totalBytes = payload.total;

        statusText = payload.status;

        if (payload.total > 0) {
          progress = (payload.downloaded / payload.total) * 100;
        }

        // Total progress (all files)
        completedFiles = payload.completed_files;
        totalFiles = payload.total_files;
        if (totalFiles > 0) {
          const currentFileFraction =
            payload.total > 0 ? payload.downloaded / payload.total : 0;
          totalProgress = ((completedFiles + currentFileFraction) / totalFiles) * 100;
        }

        // Calculate download speed (using moving average)
        totalDownloadedBytes = payload.total_downloaded_bytes;
        const now = Date.now();
        const timeDiff = (now - lastUpdateTime) / 1000; // seconds
        
        if (timeDiff >= 0.5) { // Update speed every 0.5 seconds
          const bytesDiff = totalDownloadedBytes - lastTotalBytes;
          const instantSpeed = bytesDiff / timeDiff;
          // Smooth the speed with exponential moving average
          downloadSpeed = downloadSpeed === 0 ? instantSpeed : downloadSpeed * 0.7 + instantSpeed * 0.3;
          lastUpdateTime = now;
          lastTotalBytes = totalDownloadedBytes;
        }

        // Estimate remaining time based on files remaining
        if (downloadSpeed > 0 && completedFiles < totalFiles) {
          // Rough estimate: assume average file size based on downloaded data
          const avgBytesPerFile = completedFiles > 0 ? totalDownloadedBytes / completedFiles : totalDownloadedBytes;
          const remainingFiles = totalFiles - completedFiles;
          const estimatedRemainingBytes = avgBytesPerFile * remainingFiles;
          etaSeconds = estimatedRemainingBytes / downloadSpeed;
        } else {
          etaSeconds = 0;
        }
      }
    );

    unlistenComplete = await listen("download-complete", () => {
      statusText = "Done!";
      progress = 100;
      totalProgress = 100;
      setTimeout(() => {
        visible = false;
      }, 2000);
    });
  });

  onDestroy(() => {
    if (unlistenProgress) unlistenProgress();
    if (unlistenStart) unlistenStart();
    if (unlistenComplete) unlistenComplete();
  });

  function formatBytes(bytes: number) {
    if (bytes === 0) return "0 B";
    const k = 1024;
    const sizes = ["B", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
  }

  function formatSpeed(bytesPerSecond: number) {
    if (bytesPerSecond === 0) return "-- /s";
    return formatBytes(bytesPerSecond) + "/s";
  }

  function formatTime(seconds: number) {
    if (seconds <= 0 || !isFinite(seconds)) return "--";
    if (seconds < 60) return `${Math.round(seconds)}s`;
    if (seconds < 3600) {
      const mins = Math.floor(seconds / 60);
      const secs = Math.round(seconds % 60);
      return `${mins}m ${secs}s`;
    }
    const hours = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    return `${hours}h ${mins}m`;
  }
</script>

{#if visible}
  <div
    class="fixed bottom-28 right-8 z-50 w-80 bg-zinc-900/90 backdrop-blur-md border border-zinc-700 rounded-lg shadow-2xl p-4 animate-in slide-in-from-right-10 fade-in duration-300"
  >
    <div class="flex items-center justify-between mb-2">
      <h3 class="text-white font-bold text-sm">Downloads</h3>
      <span class="text-xs text-zinc-400">{statusText}</span>
    </div>

    <!-- Total Progress Bar -->
    <div class="mb-3">
      <div class="flex justify-between text-[10px] text-zinc-400 mb-1">
        <span>Total Progress</span>
        <span>{completedFiles} / {totalFiles} files</span>
      </div>
      <div class="w-full bg-zinc-800 rounded-full h-2.5 overflow-hidden">
        <div
          class="bg-gradient-to-r from-blue-500 to-cyan-400 h-2.5 rounded-full transition-all duration-200"
          style="width: {totalProgress}%"
        ></div>
      </div>
      <div class="flex justify-between text-[10px] text-zinc-500 font-mono mt-0.5">
        <span>{formatSpeed(downloadSpeed)} · ETA: {formatTime(etaSeconds)}</span>
        <span>{completedFiles < totalFiles ? Math.floor(totalProgress) : 100}%</span>
      </div>
    </div>

    <div class="text-xs text-zinc-300 truncate mb-1" title={currentFile}>
      {currentFile || "Waiting..."}
    </div>

    <!-- Current File Progress Bar -->
    <div class="w-full bg-zinc-800 rounded-full h-2 mb-2 overflow-hidden">
      <div
        class="bg-gradient-to-r from-green-500 to-emerald-400 h-2 rounded-full transition-all duration-200"
        style="width: {progress}%"
      ></div>
    </div>

    <div class="flex justify-between text-[10px] text-zinc-500 font-mono">
      <span>{formatBytes(downloadedBytes)} / {formatBytes(totalBytes)}</span>
      <span>{Math.round(progress)}%</span>
    </div>
  </div>
{/if}
